### ISSUE TITLE
Dedicated naming format for Volume As Issue files

### ISSUE THREAD

**Issue by Colin1224** [Casvt/Kapowarr#195]
**Description of the bug**

I'm having issues surrounding "Volume as issue" and "Treat Volume Issues As 'No Title'".  When I have a volume in kapowarr that's a volume of volumes (such as [Reign of X](https://comicvine.gamespot.com/reign-of-x/4050-137265/)), and it's in the "Volume as issue" special state and "Treat Volume Issues As 'No Title'" is unchecked in the settings, I am unable to download through kapowarr for that volume or rename files that I download manually for that volume. 

In addition, when "Treat Volume Issues As 'No Title'" is checked, kapowarr seems to sometimes treat the volume issues as regular issues and not as "Issues Without Title" like the settings page would suggest. The reason for this seems to be that sometimes volumes issues are named "Vol. N" such as in [Batgirls](https://comicvine.gamespot.com/batgirls/4050-146597/) and it seems that only volume as issue series that have exactly "Volume N" naming (such as Reign of X) are properly treated as volume issues.

**To Reproduce**

1. Go to settings and uncheck "Treat Volume Issues As 'No Title'"
2. Add volume [Reign of X](https://comicvine.gamespot.com/reign-of-x/4050-137265/)
3. Set volume's "Special State" to "Volume as Issue"
4. Attempt to download any volume issue
5. See first error (wheel spins indefinitely when you manually search and click download)
6. Manually download a volume issue and put it in your volume folder
7. Press "Preview Rename"
8. See second error (nothing happens with either volume of volumes that I tried)
9. Go to settings and check "Treat Volume Issues As 'No Title'"
10. Go back to previous volume and press "Preview Rename"
11. Preview rename should work now
12. Add volume [Batgirls](https://comicvine.gamespot.com/batgirls/4050-146597/)
13. Download any of the volume issues
14. See that volume issue is named as a regular issue instead of as an issue with no title because the volume issue title for Batgirls is "Vol. N" instead of "Volume N"

**Expected behaviour**

For whatever reason when a volume is in "Volume as issue" special state and "Treat Volume Issues As 'No Title'" is unchecked I can't download anything for that volume and I would expect to be able to download something. In addition I don't see any good reason why renaming shouldn't work in that scenario so I assume that's also a bug. As for the "Treat Volume Issues As 'No Title'"  I think that "Vol. N" and "Vol N" should be added as possible volume issue names (at least I'm pretty sure that's what's going on).

I believe that it would be appropriate to have a "Volume as Issue" special state naming schema in addition to the three already available, in order to make everything easier.

**Version info**

```
Kapowarr version 	v1.0.0

Python version 	3.8.17.final.0

Database version 	27

Database location 	/app/db/Kapowarr.db

Data folder 	/app
```

Hosted on Docker for windows, WSL backend. Accessed via firefox.

**Comment by Casvt** [comment]
I cannot reproduce error 1. There was some strange stuff going on though because Pixeldrain folders weren't supported, so Kapowarr downloaded an html file. Maybe that had to do with it? Anyway, I added support for PixelDrain folders in commit 3e556860f359894cdaef48d4363b97aac9c2c9e8.

On top of that commit, I also found a bug with downloading Volume as Issue's (VAI) from GC where there are downloads for all of them and individual downloads (like on the Reign of X page), that lead to both of them being downloaded. That is fixed in 1a2d004f25336b1f6ee9dcdb9cf738c09286c95b.

When I added Batgirls, I couldn't download the TPB's because the Special Version (SV) wasn't determined correctly. Turns out it would only detect it if the issue names were `Volume N`, not `Vol N` or `V N`. Fixed that in commit 50d5861fd3796affa4de84a23e78242ceb854607.

Turns out that the wrong naming of VAI issues (as described in your bullet 14) is a result of the volume not correctly being marked as a VAI. As this was fixed by the commit mentioned in the previous paragraph, nothing has to be done to fix this anymore (except I removed some code that wasn't used in commit 276a55f693a14facea8304823fbec9b14f8d873d).

I do agree that a dedicated naming format for VAI issues should be made. I'll turn this issue into a feature request for that.

**Comment by Colin1224** [comment]
Thanks for fixing those issues so quickly.

So I did a fresh manual install of kapowarr on Arch linux with the latest commit and the issue of not being able to download Batgirls Volume as Issue when "Treat Volume Issues As 'No Title'" isnt't checked still exists. I realized that I forgot to pull logs when I created the issue. When I do a manual search and click download I get this error.

```
2024-11-01T20:07:29-0700 | MainProcess | waitress-9 | search.pyL289 | INFO | Starting manual search: Batgirls (2022) 
2024-11-01T20:07:33-0700 | MainProcess | waitress-6 | download_queue.pyL422 | INFO | Adding download for volume 1 issue 1: https://getcomics.org/dc/batgirls-vol-1-tpb-2022/
2024-11-01T20:07:33-0700 | MainProcess | waitress-6 | app.pyL838 | ERROR | Exception on /api/issues/1/download [POST]
Traceback (most recent call last):
  File "/home/colin1224/.pyenv/versions/3.8.17/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/colin1224/.pyenv/versions/3.8.17/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/colin1224/.pyenv/versions/3.8.17/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/colin1224/.pyenv/versions/3.8.17/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/colin1224/repos/Kapowarr/frontend/api.py", line 78, in wrapper
    return method(*args, **kwargs)
  File "/home/colin1224/repos/Kapowarr/frontend/api.py", line 234, in wrapper
    result = method(*args, **kwargs)
  File "/home/colin1224/repos/Kapowarr/frontend/api.py", line 798, in api_issue_download
    result = download_handler.add(link, volume_id, id)
  File "/home/colin1224/repos/Kapowarr/backend/download_queue.py", line 437, in add
    downloads = gcp.create_downloads(
  File "/home/colin1224/repos/Kapowarr/backend/getcomics.py", line 784, in create_downloads
    result, limit_reached = _test_paths(
  File "/home/colin1224/repos/Kapowarr/backend/getcomics.py", line 583, in _test_paths
    name = _generate_name(
  File "/home/colin1224/repos/Kapowarr/backend/getcomics.py", line 403, in _generate_name
    return generate_empty_name(
  File "/home/colin1224/repos/Kapowarr/backend/naming.py", line 272, in generate_empty_name
    sv_l.remove('None')
ValueError: list.remove(x): x not in list
```

The same error occurs on my older docker install on windows.


Also I pulled the logs for the renaming issue I was having. When I have nothing in the volume folder for Batgirls and click "Preview Rename" it comes up without issue, but when I put files in the volume folder and click "Preview Rename" nothing visually happens and this error appears in the logs:

```
2024-11-01T20:22:55-0700 | MainProcess | waitress-4 | api.pyL225 | DEBUG | GET /api/volumes/1/rename
2024-11-01T20:22:55-0700 | MainProcess | waitress-4 | naming.pyL523 | DEBUG | Renaming: original filename: /home/colin1224/repos/Kapowarr/downloads/Batgirls (2022)/Batgirls (2022) - #001 - (2022-11-29) [957994].cbz
2024-11-01T20:22:55-0700 | MainProcess | waitress-4 | app.pyL838 | ERROR | Exception on /api/volumes/1/rename [GET]
Traceback (most recent call last):
  File "/home/colin1224/.pyenv/versions/3.8.17/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/colin1224/.pyenv/versions/3.8.17/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/colin1224/.pyenv/versions/3.8.17/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/colin1224/.pyenv/versions/3.8.17/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/colin1224/repos/Kapowarr/frontend/api.py", line 78, in wrapper
    return method(*args, **kwargs)
  File "/home/colin1224/repos/Kapowarr/frontend/api.py", line 234, in wrapper
    result = method(*args, **kwargs)
  File "/home/colin1224/repos/Kapowarr/frontend/api.py", line 716, in api_rename
    result = preview_mass_rename(id)[0]
  File "/home/colin1224/repos/Kapowarr/backend/naming.py", line 555, in preview_mass_rename
    suggested_name = generate_empty_name(
  File "/home/colin1224/repos/Kapowarr/backend/naming.py", line 272, in generate_empty_name
    sv_l.remove('None')
ValueError: list.remove(x): x not in list
```

**Comment by Casvt** [comment]
Confession time! How the naming works of VAI when the setting is disabled is that we generate the name using the Special Version format and then remove the special version string. It's extremely hacky and it's why we need a dedicated VAI naming format.

The error is because it cannot find the special version string in the generated filename. What is your special version naming format?

**Comment by Colin1224** [comment]
My special version naming format is `{clean_series_name} ({year}) - v{volume_number}`. I just tried adding `{special_version}` and renaming worked.

Maybe it would be a good idea to add a mandatory check for `{special_version}` in the special version naming format until the VAI naming format is available?

**Comment by Colin1224** [comment]
Also, should the special version naming format be missing tags like `{issue_comicvine_id}, {issue_number}, {issue_title}, {issue_release_date}, and {issue_release_year}`? Because even for volumes with only a TPB in them (eg [A Very DC Rebirth Holiday](https://comicvine.gamespot.com/a-very-dc-rebirth-holiday/4050-105779/)) the TPB still has a release date that's more specific than just the year as well as a comic vine ID that's separate from the volume ID. Like for example above example the volume ID is 4050-105779 and the TPB ID is 4000-634523. These are separate of the original series comic vine ID ([4050-96654](https://comicvine.gamespot.com/dc-rebirth-holiday-special/4050-96654/)).

Is there a reason why these can't be used?

**Comment by Casvt** [comment]
> Maybe it would be a good idea to add a mandatory check for `{special_version}` in the special version naming format until the VAI naming format is available?

On my to-do list is format validation. So we use the supplied format and see if it is sufficient for matching files using the format (i.e. if Kapowarr supports the format). If it's not, reject it.

> Also, should the special version naming format be missing tags like {issue_comicvine_id}, {issue_number}, {issue_title}, {issue_release_date}, and {issue_release_year}?

I guess they can be used, except for the issue number (because TPB's dont match when an issue number is given).
